version: '3.3'
services:
    php:
        image: php:7.4-apache
        volumes:
            - ./webserverdata:/var/www/html/
            - ./sites-available:/etc/apache2/sites-available/
        ports:
            - 8000:80
        networks:
            - dev
        build: .
    db:
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - dev
        volumes:
            - ./bddata:/var/lib/mysql
            - ./bdimport:/docker-entrypoint-initdb.d
        ports:
            - 4000:3306
    myadmin:
        image: phpmyadmin/phpmyadmin:latest
        networks:
            - dev
        ports:
        -    4001:80
        environment:
            - PMA_ARBITRARY=1

    composer:
        image: prooph/composer:7.2
        volumes:
            - ./webserverdata/projects/playlistShare/backend:/playlistShare
        working_dir: /playlistShare
        command: install

    yt-convert-service:
        environment:
            - API_KEY=Insert your API key here from google
        build: .
        networks:
            - dev
        volumes:
            - ./youtubedownloader:/var/www/html
        ports:
            - '4003:80'

    composer:
        image: prooph/composer:7.2
        volumes:
            - ./youtubedownloader:/yt
        working_dir: /yt/
        command: install

networks:
    dev:
        driver: bridge

volumes:
    phpdata:
    bddata:
    bdimport:
    youtubedownloader:
    sites-available:
    webserverdata: